bytedance/matxscript

include/matxscript/runtime/c_runtime_api.h, include/matxscript/runtime/container/ndarray.h, include/matxscript/runtime/container/ndarray_helper.h, include/matxscript/runtime/container/ndarray_private.h, include/matxscript/runtime/device_api.h, include/matxscript/runtime/dlpack.h, python/matx/_ffi/_c_ext/fast_c_api.cc, python/matx/extension/cpp/pytorch/src/tensor_api.cc, python/matx/extension/cpp/pytorch/src/torch_infer_op.cc, python/matx/extension/cpp/pytorch/src/torch_infer_op.h, python/matx/extension/cpp/tensorflow/src/tf_utils.cc, src/c_api/ndarray_c_api.cc, src/c_api/pipeline_c_api.cc, src/c_api/stream_c_api.cc, src/pipeline/device_op.cc, src/pipeline/pickle.cc, src/pipeline/tx_session.cc, src/runtime/c_runtime_api.cc, src/runtime/container/ndarray.cc, src/runtime/container/ndarray_helper.cc, src/runtime/container/ndarray_operator.cc, src/runtime/cpu_device_api.cc, src/runtime/cuda/cuda_device_api.cc, src/runtime/device_api.cc, src/runtime/generic/generic_constructor_funcs.cc, src/runtime/generic/generic_funcs.cc
=> [runtime] Bump dlpack.h to latest version

python/matx/cfg/builder.py, python/matx/cfg/model.py, test/script/test_cfg_analysis.py
- used to support dynamic types
- #57
=> [script] reaching define analysis

src/runtime/generic/generic_constructor_funcs.cc
=> [runtime] ndarray constructor: allow explicit shape

python/matx/cfg/builder.py, python/matx/script/analysis/__init__.py, python/matx/script/analysis/live_variable_analysis.py, python/matx/script/parser.py, test/script/test_dynamic_var_type.py, test/script/test_error_report.py
=> [script] improve basic support for dynamic type variable

python/matx/text/__init__.py, python/matx/text/wordpiece_tokenizer.py, test/script/test_builtin_text_ops.py
=> [text] clean code

ci/build_pcre.sh
=> [build] rename soname when build pcre on macos

python/matx/__init__.py
- Fix pypi install bug on macos.
=> Release 1.8.1

src/pipeline/tx_session.cc
=> Add an option for disable sharing JitObject between sessions

include/matxscript/ir/prim_var.h, src/ir/prim_var.cc
- will be used in MapBlockStmt and ForStmt
=> [ir] add PrimIterVar which is originally from tvm/main

include/matxscript/ir/prim_ops.h, include/matxscript/ir/stmt_functor.h, include/matxscript/ir/tensor_stmt.h, python/matx/ir/expr.py, python/matx/ir/tensor_stmt.py, src/ir/stmt_functor.cc, src/ir/tensor_stmt.cc
- follow tvm: https://github.com/apache/tvm/pull/7553, with change applied
- Rename Block to ComputeBlock
- Keep the minimal implementation and remove designs that are not currently used
=> [ir] introduce tensor stmts

include/matxscript/ir/_base/cow_map_ref.h, include/matxscript/ir/_base/text_printer.h, include/matxscript/runtime/object.h, src/ir/_base/text_printer.cc, src/ir/printer/doc.cc, src/ir/printer/doc.h, src/ir/printer/doc_printer/base_doc_printer.cc, src/ir/printer/doc_printer/base_doc_printer.h, src/ir/printer/doc_printer/python_doc_printer.cc, src/ir/printer/ir_docsifier.cc, src/ir/printer/ir_docsifier.h, src/ir/printer/ir_docsifier_functor.h, src/ir/printer/utils.h
**Follow TVMScript Unified Printer**
-------------------------------------
- TVM RFC: https://github.com/apache/tvm-rfcs/pull/79
- https://github.com/apache/tvm/issues/11912
=> [IR] Refactor IR Printer: new Doc, DocPrinter and IRDocisifer

include/matxscript/ir/printer/ir_frame.h, include/matxscript/ir/printer/utils.h, src/ir/printer/text_printer.cc, src/ir/stmt.cc
**Follow TVMScript Unified Printer**
-------------------------------------
- TVM RFC: https://github.com/apache/tvm-rfcs/pull/79
- https://github.com/apache/tvm/issues/11912
=> [IR] Refactor IR Printer: Basic Stmt to Doc

python/matx/toolchain.py, python/matx/utils.py, test/script/test_cache_so.py
Try to control matx log amount by setting a customized logger level in Python
=> Added a customized logger level matx_info for logging matx related info message

src/codegen/codegen_c.cc, src/ir/const_fold.h, src/ir/int_operator.h, src/ir/prim_expr.cc, src/ir/prim_ops.cc, src/ir/printer/doc_printer/python_doc_printer.cc, test/script/test_arith_fold.py
- fix printer
- fix constant fold
=> [IR] fix floormod, floordiv, div

python/matx/kernel/parser/base_parser.py, python/matx/kernel/parser/for_loop_parser.py, python/matx/kernel/parser/kernel_parser2.py, python/matx/kernel/parser/utils.py
- simple for loops are supported
- nested for loops are supported
- some scalar operations are supported 
- not support indexing ndarray yet
=> [IR] kernel basic for-loop support

python/matx/kernel/parser/single_return_parser.py, test/kernel/test_kernel_single_return_parser.py
- fixed a bug that caused bin ops failing
- fixed a bug that caused the segmentation fault
- added unit tests for single return parser
=> [IR] kernel parser tests

python/matx/kernel/parser/base_parser.py, python/matx/kernel/parser/context.py, test/kernel/test_kernel_for_loop_parser.py
The for-loop parser is now supporting nd indexing
=> [IR] kernel parser nd indexing

src/ir/printer/linalg_printer.cc, test/script/test_linalg_printer.py
for basic arithmetic operation like (a+b)*(c-d)/e, generate linalg related statement.
=> [linalg]: support arith op

python/matx/kernel/ir/utils.py, python/matx/kernel/parser/base_parser.py, python/matx/kernel/parser/for_loop_parser.py, python/matx/kernel/typing/utils.py, test/kernel/test_kernel_for_loop_parser.py
add symbolic expression support in range function
=> [IR] kernel support symbolic expression in for-loop range

include/matxscript/ir/function.h, include/matxscript/ir/printer/kernel_printer/mlir_printer.h, python/matx/ir/function.py, python/matx/kernel/ir/ndarray.py, python/matx/kernel/parser/base_parser.py, src/ir/printer/kernel_printer/linalg_generic_printer.cc, src/ir/printer/kernel_printer/mlir_printer.cc
1. Bind ndarray parameters with buffer and use to determine the number of dimension
=> [Kernel] buffer binding

include/matxscript/ir/printer/text_printer.h, src/ir/function.cc
=> fix: support gcc492 compile

python/matx/vision/cast_op.py
Hi, this is a PR from bytedance.
=> fix CastOp typo
